function toggleMenu(){const nav=document.getElementById("mainNav");if(nav)nav.classList.toggle("show")}
function selectSchool(s){localStorage.setItem("selectedSchool",s);localStorage.removeItem("selectedClass");location.href="classes.html"}
function searchSchools(){const input=document.getElementById("schoolSearch"),cards=document.querySelectorAll(".school-card"),empty=document.getElementById("noSchools");if(!input)return;let q=input.value.toLowerCase().trim(),found=0;cards.forEach(c=>{const ok=c.dataset.school.toLowerCase().includes(q);c.style.display=ok?"":"none";if(ok)found++});if(empty)empty.classList.toggle("hidden",found!==0)}
function selectClass(c){if(!localStorage.getItem("selectedSchool")){alert("Please select your school first.");location.href="schools.html";return}localStorage.setItem("selectedClass",c);location.href="products.html"}

const products=[
{id:1,name:"English Textbook",category:"Books",price:450,icon:"📘",description:"School prescribed English textbook."},
{id:2,name:"Mathematics Textbook",category:"Books",price:480,icon:"📐",description:"Complete mathematics textbook."},
{id:3,name:"Science Textbook",category:"Books",price:520,icon:"🔬",description:"School science textbook."},
{id:4,name:"Social Studies Book",category:"Books",price:430,icon:"🌍",description:"Social studies textbook."},
{id:5,name:"Class Notebook - Single Line",category:"Notebooks",price:55,icon:"📓",description:"High quality school notebook."},
{id:6,name:"Class Notebook - Four Line",category:"Notebooks",price:60,icon:"📔",description:"Four line notebook for students."},
{id:7,name:"Homework Notebook",category:"Notebooks",price:50,icon:"📒",description:"Homework and practice notebook."},
{id:8,name:"School Shirt",category:"Uniform",price:450,icon:"👕",description:"Official school uniform shirt."},
{id:9,name:"School Trousers",category:"Uniform",price:650,icon:"👖",description:"Official school uniform trousers."},
{id:10,name:"School Skirt",category:"Uniform",price:600,icon:"👗",description:"Official school uniform skirt."},
{id:11,name:"School Sweater",category:"Uniform",price:850,icon:"🧥",description:"Winter school sweater."},
{id:12,name:"Classic School Backpack",category:"Bags",price:899,icon:"🎒",description:"Durable school backpack."},
{id:13,name:"Premium School Backpack",category:"Bags",price:1299,icon:"🎒",description:"Premium large school backpack."},
{id:14,name:"Pencil Box",category:"Stationery",price:149,icon:"🖍️",description:"Multi-compartment pencil box."},
{id:15,name:"Geometry Box",category:"Stationery",price:199,icon:"📏",description:"Complete geometry set."},
{id:16,name:"Pen & Pencil Set",category:"Stationery",price:120,icon:"✏️",description:"Student writing stationery set."},
{id:17,name:"School Water Bottle",category:"Stationery",price:299,icon:"🥤",description:"Leak-proof school bottle."},
{id:18,name:"School Shoes",category:"Shoes",price:799,icon:"👟",description:"Comfortable black school shoes."},
{id:19,name:"Sports Shoes",category:"Shoes",price:999,icon:"👟",description:"School sports shoes."}
];

function getCart(){try{return JSON.parse(localStorage.getItem("schoolCart")||"[]")}catch(e){return[]}}
function saveCart(c){localStorage.setItem("schoolCart",JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,i)=>s+i.quantity,0);document.querySelectorAll(".cart-count").forEach(e=>e.textContent=n)}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;let c=getCart(),e=c.find(x=>x.id===id);if(e)e.quantity++;else c.push({...p,quantity:1});saveCart(c);showToast(p.name+" added to cart!")}
function addCompleteKit(){let c=getCart(),e=c.find(x=>x.id===999);if(e)e.quantity++;else c.push({id:999,name:"Complete School Kit",category:"Complete Kit",price:2999,icon:"🎁",quantity:1});saveCart(c);showToast("Complete School Kit added!")}
let currentCategory="All";
function renderProducts(cat="All"){const grid=document.getElementById("productGrid");if(!grid)return;const search=(document.getElementById("productSearch")?.value||"").toLowerCase().trim();const list=products.filter(p=>(cat==="All"||p.category===cat)&&(p.name.toLowerCase().includes(search)||p.category.toLowerCase().includes(search)));grid.innerHTML=list.map(p=>`<div class="product-card"><div class="product-image">${p.icon}</div><div class="product-info"><span class="product-category">${p.category}</span><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><span class="price">₹${p.price.toLocaleString("en-IN")}</span><button class="add-btn" onclick="addToCart(${p.id})">+ Add</button></div></div></div>`).join("");document.getElementById("noProducts")?.classList.toggle("hidden",list.length!==0)}
function filterProducts(cat,btn){currentCategory=cat;document.querySelectorAll(".category-btn").forEach(b=>b.classList.remove("active"));btn?.classList.add("active");renderProducts(cat)}
function searchProducts(){renderProducts(currentCategory)}
function renderCart(){const c=getCart(),content=document.getElementById("cartContent"),empty=document.getElementById("emptyCart"),items=document.getElementById("cartItems");if(!items)return;if(!c.length){content.classList.add("hidden");empty.classList.remove("hidden");return}content.classList.remove("hidden");empty.classList.add("hidden");let sub=0,count=0;items.innerHTML=c.map(i=>{sub+=i.price*i.quantity;count+=i.quantity;return`<div class="cart-item"><div class="cart-item-image">${i.icon}</div><div><h3>${i.name}</h3><p>${i.category}</p><div class="quantity"><button onclick="changeQuantity(${i.id},-1)">−</button><strong>${i.quantity}</strong><button onclick="changeQuantity(${i.id},1)">+</button></div><button class="remove-btn" onclick="removeFromCart(${i.id})">Remove</button></div><div class="cart-price">₹${(i.price*i.quantity).toLocaleString("en-IN")}</div></div>`}).join("");const delivery=sub>=1500?0:50;document.getElementById("subtotal").textContent="₹"+sub.toLocaleString("en-IN");document.getElementById("delivery").textContent=delivery?"₹"+delivery:"FREE";document.getElementById("discount").textContent="₹0";document.getElementById("total").textContent="₹"+(sub+delivery).toLocaleString("en-IN");document.getElementById("cartItemCount").textContent=count+(count===1?" item":" items")}
function changeQuantity(id,d){let c=getCart(),i=c.find(x=>x.id===id);if(!i)return;i.quantity+=d;if(i.quantity<=0)c=c.filter(x=>x.id!==id);saveCart(c);renderCart()}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart();showToast("Item removed.")}
function checkout(){if(!getCart().length)return alert("Your cart is empty.");if(localStorage.getItem("loggedIn")!=="true"){localStorage.setItem("redirectAfterLogin","cart.html");alert("Please login before checkout.");location.href="login.html";return}alert("Checkout will be connected to payment and address system in the next version.")}
function loginUser(e){e.preventDefault();const email=document.getElementById("loginEmail").value,pw=document.getElementById("loginPassword").value;if(!email||!pw)return alert("Please fill all fields.");localStorage.setItem("loggedIn","true");localStorage.setItem("userEmail",email);showToast("Login successful!");setTimeout(()=>location.href=localStorage.getItem("redirectAfterLogin")||"index.html",700);localStorage.removeItem("redirectAfterLogin")}
function signupUser(e){e.preventDefault();localStorage.setItem("loggedIn","true");localStorage.setItem("userName",document.getElementById("signupName").value);localStorage.setItem("userEmail",document.getElementById("signupEmail").value);localStorage.setItem("userMobile",document.getElementById("signupMobile").value);showToast("Account created successfully!");setTimeout(()=>location.href="index.html",700)}
function showSignup(){document.getElementById("loginForm")?.classList.add("hidden");document.getElementById("signupForm")?.classList.remove("hidden");if(document.getElementById("authTitle"))document.getElementById("authTitle").textContent="Create Your Account";if(document.getElementById("authSubtitle"))document.getElementById("authSubtitle").textContent="Create an account to start shopping."}
function showLogin(){document.getElementById("loginForm")?.classList.remove("hidden");document.getElementById("signupForm")?.classList.add("hidden");if(document.getElementById("authTitle"))document.getElementById("authTitle").textContent="Welcome Back!";if(document.getElementById("authSubtitle"))document.getElementById("authSubtitle").textContent="Login to continue shopping."}
function demoLogin(){localStorage.setItem("loggedIn","true");localStorage.setItem("userName","Demo Parent");showToast("Demo login successful!");setTimeout(()=>location.href="index.html",700)}
function forgotPassword(e){e.preventDefault();alert("Password recovery will be connected to email/OTP in the backend version.")}
function showToast(msg){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";Object.assign(t.style,{position:"fixed",bottom:"25px",right:"25px",background:"#0f172a",color:"white",padding:"13px 20px",borderRadius:"9px",fontSize:"14px",fontWeight:"700",zIndex:"99999",boxShadow:"0 10px 30px rgba(0,0,0,.2)"});document.body.appendChild(t)}t.textContent=msg;t.style.display="block";clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display="none",2200)}
function initializeProductsPage(){const school=localStorage.getItem("selectedSchool"),cls=localStorage.getItem("selectedClass");const h=document.getElementById("productHeading"),s=document.getElementById("productSubheading");if(h)h.textContent=school&&cls?school+" — "+cls:"School Products";if(s)s.textContent=school&&cls?"Books, notebooks, uniforms and essentials for "+cls+".":"Find everything your child needs.";renderProducts("All");const cat=new URLSearchParams(location.search).get("category");if(cat){const b=[...document.querySelectorAll(".category-btn")].find(x=>x.textContent.toLowerCase().includes(cat.toLowerCase()));filterProducts(cat,b)}}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();initializeProductsPage()});
